name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Set API key environment variable
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> npcampground/.env

      - name: Install dependencies and build
        working-directory: npcampground
        run: |
          npm install
          npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: npcampground
          destination: npcampground/_site
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: site
          path: npcampground/_site
          if-no-files-found: error 
          retention-days: 7
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.2
        with:
          name: github-pages
          path: npcampground/_site
                   
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: site
          preview: false
  
